name: story
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11.3
  - pip:
    - pycocotools==2.0.7
    - transformers==4.27.1
    - accelerate==0.20.3
    - bitsandbytes==0.41.1
    - torch==2.0.1
    - omegaconf==2.3.0
    - iopath==0.1.10
    - wandb
